# Auto-generated field name to ID mapping
FIELD_NAME_TO_NUMBER = {
    "ACAS_GENERATION/SEGMENT_NUMBER:": "34",
    "ACAS_POINTER_BACK_TO_PREVIOUS_GEN/SEG:": "35",
    "ACTION_OR_REASON_CODE_1:": "88",
    "ACTION_OR_REASON_CODE_2:": "89",
    "ACTION_OR_REASON_CODE_3:": "90",
    "ADJUSTMENT_CODE:": "8",
    "ADMINISTRATIVE_SAVINGS_AMOUNT:": "117",
    "ADMISSION_DATE:": "142",
    "ADMIT_COUNTER:": "116",
    "AETNA_HEALTH_FUND_-_PAYABLE_AMOUNT:": "103",
    "AETNA_HEALTH_FUND_DETERMINATION_ORDER_CODE:": "169",
    "AETNA_HEALTH_FUND_MEMBER_COPAY_AMOUNT:": "171",
    "AETNA_HEALTH_FUND_MEMBER_DEDUCTIBLE_AMOUNT:": "172",
    "AETNA_HEALTH_FUND_MEMBER_SHARE_OF_COINSURANCE_AMOUNT:": "170",
    "AETNA_HEALTH_FUND_–_BEFORE_FUND_DEDUCTIBLE:": "102",
    "AEXCEL_BENEFIT_TIER_CODE:": "120",
    "AEXCEL_DESIGNATED_PROVIDER_SPECIALTY:": "121",
    "AEXCEL_PLAN_DESIGN_CODE:": "119",
    "AEXCEL_PROVIDER_DESIGNATION_CODE:": "118",
    "ALLOWED_AMOUNT:": "92",
    "ASSIGNMENT_OF_BENEFITS_TO_PROVIDER_CODE:": "56",
    "BENEFIT_IDENTIFICATION_CODE": "13",
    "BENEFIT_PAYABLE:": "99",
    "BENEFIT_TIER:": "15",
    "BILLED_ELIGIBLE_AMOUNT:": "123",
    "CLAIM-LEVEL_ICD_PROCEDURE_CODE_1:": "163",
    "CLAIM-LEVEL_ICD_PROCEDURE_CODE_2:": "164",
    "CLAIM-LEVEL_ICD_PROCEDURE_CODE_3:": "165",
    "CLAIM-LEVEL_ICD_PROCEDURE_CODE_4:": "166",
    "CLAIM-LEVEL_ICD_PROCEDURE_CODE_5:": "167",
    "CLAIM-LEVEL_ICD_PROCEDURE_CODE_6:": "168",
    "CLAIM_LINE_ID": "38",
    "CLASSIFICATION_CODE:": "12",
    "COB_CODE:": "110",
    "COB_PAID_AMOUNT:": "101",
    "COPAYMENT_AMOUNT:": "94",
    "COVERAGE/ENROLLMENT_TIER:": "24",
    "COVERED_EXPENSE:": "91",
    "DATE_CLAIM_SUBMISSION_RECEIVED:": "58",
    "DATE_PROCESSED": "62",
    "DATE_SERVICE_STARTED:": "60",
    "DATE_SERVICE_STOPPED:": "61",
    "DEDUCTIBLE_AMOUNT:": "96",
    "DIAGNOSIS_CODE_10:": "162",
    "DIAGNOSIS_CODE_1:": "153",
    "DIAGNOSIS_CODE_2:": "154",
    "DIAGNOSIS_CODE_3:": "155",
    "DIAGNOSIS_CODE_4:": "156",
    "DIAGNOSIS_CODE_5:": "157",
    "DIAGNOSIS_CODE_6:": "158",
    "DIAGNOSIS_CODE_7:": "159",
    "DIAGNOSIS_CODE_8:": "160",
    "DIAGNOSIS_CODE_9:": "161",
    "DIAGNOSIS_RELATED_GROUP": "67",
    "DISCHARGE_DATE:": "143",
    "EMPLOYEE_SSN:": "17",
    "END_OF_RECORD_MARKER:": "178",
    "EXCHANGE_IDENTIFIER:": "176",
    "EXPENSE/PAY_LINE_NUMBER:": "37",
    "FUNDING_ARRANGEMENT:": "16",
    "GENERAL_CATEGORY_OF_HEALTH_PLAN:": "10",
    "GROSS_SUBMITTED_EXPENSE:": "83",
    "HCFA_ADMIT_SOURCE_CODE:": "140",
    "HCFA_ADMIT_TYPE_CODE:": "141",
    "HCFA_PLACE_OF_SERVICE_CODE:": "139",
    "HIERARCHY_LEVEL_3:": "3",
    "HIERARCHY_LEVEL_5:": "5",
    "HIERARCHY_LEVEL_6": "6",
    "ICD-10_INDICATOR:": "175",
    "LINE-LEVEL_PROCEDURE_CODE": "68",
    "LINE-LEVEL_PROCEDURE_CODE_MODIFIER": "145",
    "LINE-LEVEL_PROCEDURE_CODE_TYPE:": "70",
    "LINE_OF_BUSINESS:": "11",
    "MAJOR_DIAGNOSTIC_CATEGORY": "66",
    "MEDICARE_CODE:": "108",
    "MEMBER_DATE_OF_BIRTH:": "32",
    "MEMBER_FIRST_NAME:": "29",
    "MEMBER_GENDER:": "30",
    "MEMBER_ID": "26",
    "MEMBER_LAST_NAME:": "28",
    "MEMBER_NETWORK_ID:": "39",
    "MEMBER_NUMBER:": "27",
    "MEMBER_RELATIONSHIP_TO_SUBSCRIBER:": "31",
    "MEMBER_SSN:": "25",
    "MEMBER_‘CUMBID’:": "112",
    "NATIONAL_DRUG_CODE:": "111",
    "NET_SUBMITTED_EXPENSE:": "84",
    "NON-SSN_SUBSCRIBER_ID:": "114",
    "NOT_COVERED_AMOUNT_1:": "85",
    "NOT_COVERED_AMOUNT_2:": "86",
    "NOT_COVERED_AMOUNT_3:": "87",
    "NUMBER/UNITS_OF_SERVICE:": "81",
    "PAID_AMOUNT:": "100",
    "PARTICIPATING_PROVIDER_CODE:": "57",
    "PCP_IRS_TAX_IDENTIFICATION_NUMBER": "43",
    "PCP_NAME": "44",
    "PLACE_OF_SERVICE:": "77",
    "PLAN_CODE_OR_EXTENSION_OF_HIERARCHY:": "14",
    "PREFERRED_VS_NON-PREFERRED_BENEFIT_LEVEL:": "9",
    "PRESENT_ON_ADMISSION_CODE": "152",
    "PRICING_METHOD_CODE:": "131",
    "PRODUCT_DISTINCTION_CODE": "122",
    "REFERRAL_TYPE:": "41",
    "REPROCESS_THE_ORIGINAL_CLAIM,_USING_THE_SAME_CLAIM_ID": "1",
    "REVERSAL_CODE:": "115",
    "SAVINGS_-_COB:": "106",
    "SAVINGS_–_NEGOTIATED_FEE:": "104",
    "SAVINGS_–_R&C:": "105",
    "SAVINGS_–_SOURCE_COB:": "107",
    "SERVICE_BENEFIT_CODE:": "75",
    "SERVICING_PROVIDER_CITY:": "51",
    "SERVICING_PROVIDER_CLASS_CODE:": "124",
    "SERVICING_PROVIDER_NAME": "48",
    "SERVICING_PROVIDER_NETWORK_ID:": "40",
    "SERVICING_PROVIDER_NPI:": "134",
    "SERVICING_PROVIDER_PIN:": "47",
    "SERVICING_PROVIDER_SPECIALTY_CATEGORY_CODE:": "133",
    "SERVICING_PROVIDER_SPECIALTY_CODE:": "55",
    "SERVICING_PROVIDER_STATE:": "52",
    "SERVICING_PROVIDER_STREET_ADDRESS_1:": "49",
    "SERVICING_PROVIDER_STREET_ADDRESS_2:": "50",
    "SERVICING_PROVIDER_TAX_ID_NUMBER": "46",
    "SERVICING_PROVIDER_TYPE:": "54",
    "SERVICING_PROVIDER_TYPE_CLASS_CODE:": "132",
    "SERVICING_PROVIDER_ZIP_CODE:": "53",
    "SOURCE-SPECIFIC_TRANSACTION_ID_NUMBER:": "33",
    "SOURCE_COINSURANCE_AMOUNT:": "98",
    "SOURCE_COPAYMENT_AMOUNT:": "95",
    "SOURCE_NUMBER/UNITS_OF_SERVICE:": "82",
    "SOURCE_SYSTEM_PLATFORM:": "7",
    "STATUS_OF_CLAIM:": "113",
    "SUBSCRIBER_DATE_OF_BIRTH:": "21",
    "SUBSCRIBER_FIRST_NAME_OR_INITIAL:": "19",
    "SUBSCRIBER_GENDER:": "20",
    "SUBSCRIBER_LAST_NAME:": "18",
    "SUBSCRIBER_STATE:": "23",
    "SUBSCRIBER_ZIP_CODE:": "22",
    "TOOTH_NUMBER:": "76",
    "TOTAL_DEDUCTIBLE_MET_INDICATOR:": "135",
    "TOTAL_INTEREST_AMOUNT:": "136",
    "TOTAL_SURCHARGE_AMOUNT:": "137",
    "TRADITIONAL_CLAIM_ID:": "36",
    "TYPE_OF_EXPENSE_-_COB:": "109",
    "TYPE_OF_SERVICE:": "74",
    "UB92_BILL_TYPE:": "80",
    "UB92_PATIENT/DISCHARGE_STATUS:": "78",
    "UB92_REVENUE_CENTER:": "79",
    "VOID_THE_ORIGINAL_CLAIM,_AND_REPROCESS_USING_A_DIFFERENT_CLAIM_ID": "2",
    "acas generation/segment number:": "34",
    "acas pointer back to previous gen/seg:": "35",
    "action or reason code 1:": "88",
    "action or reason code 2:": "89",
    "action or reason code 3:": "90",
    "adjustment code:": "8",
    "administrative savings amount:": "117",
    "admission date:": "142",
    "admit counter:": "116",
    "aetna health fund - payable amount:": "103",
    "aetna health fund determination order code:": "169",
    "aetna health fund member copay amount:": "171",
    "aetna health fund member deductible amount:": "172",
    "aetna health fund member share of coinsurance amount:": "170",
    "aetna health fund – before fund deductible:": "102",
    "aexcel benefit tier code:": "120",
    "aexcel designated provider specialty:": "121",
    "aexcel plan design code:": "119",
    "aexcel provider designation code:": "118",
    "allowed amount:": "92",
    "assignment of benefits to provider code:": "56",
    "benefit identification": "13",
    "benefit identification code": "13",
    "benefit payable:": "99",
    "benefit tier:": "15",
    "billed eligible amount:": "123",
    "claim line id": "38",
    "claim-level icd procedure code 1:": "163",
    "claim-level icd procedure code 2:": "164",
    "claim-level icd procedure code 3:": "165",
    "claim-level icd procedure code 4:": "166",
    "claim-level icd procedure code 5:": "167",
    "claim-level icd procedure code 6:": "168",
    "classification code:": "12",
    "cob code:": "110",
    "cob paid amount:": "101",
    "coinsurance:": "97",
    "copayment amount:": "94",
    "coverage/enrollment tier:": "24",
    "covered expense:": "91",
    "date claim submission received:": "58",
    "date processed": "62",
    "date service started:": "60",
    "date service stopped:": "61",
    "deductible amount:": "96",
    "diagnosis code 10:": "162",
    "diagnosis code 1:": "153",
    "diagnosis code 2:": "154",
    "diagnosis code 3:": "155",
    "diagnosis code 4:": "156",
    "diagnosis code 5:": "157",
    "diagnosis code 6:": "158",
    "diagnosis code 7:": "159",
    "diagnosis code 8:": "160",
    "diagnosis code 9:": "161",
    "diagnosis related group": "67",
    "discharge date:": "143",
    "employee ssn:": "17",
    "end of record marker:": "178",
    "exchange identifier:": "176",
    "expense/pay line number:": "37",
    "filler:": "177",
    "funding arrangement:": "16",
    "general category of health plan:": "10",
    "gross submitted expense:": "83",
    "hcfa admit source code:": "140",
    "hcfa admit type code:": "141",
    "hcfa place of service code:": "139",
    "hierarchy level 3:": "3",
    "hierarchy level 5:": "5",
    "hierarchy level 6": "6",
    "icd-10 indicator:": "175",
    "line of business:": "11",
    "line-level procedure": "68",
    "line-level procedure code": "68",
    "line-level procedure code modifier": "145",
    "line-level procedure code type:": "70",
    "major diagnostic category": "66",
    "medicare code:": "108",
    "member date of birth:": "32",
    "member first name:": "29",
    "member gender:": "30",
    "member id": "26",
    "member last name:": "28",
    "member network id:": "39",
    "member number:": "27",
    "member relationship to subscriber:": "31",
    "member ssn:": "25",
    "member ‘cumbid’:": "112",
    "national drug code:": "111",
    "net submitted expense:": "84",
    "non-ssn subscriber id:": "114",
    "not covered amount 1:": "85",
    "not covered amount 2:": "86",
    "not covered amount 3:": "87",
    "number/units of service:": "81",
    "paid amount:": "100",
    "participating provider code:": "57",
    "pcp irs tax identification number": "43",
    "pcp name": "44",
    "place of service:": "77",
    "plan code or extension of hierarchy:": "14",
    "preferred vs non-preferred benefit level:": "9",
    "present on admission": "152",
    "present on admission code": "152",
    "pricing method code:": "131",
    "product distinction": "122",
    "product distinction code": "122",
    "referral type:": "41",
    "reprocess the original claim, using the same claim id": "1",
    "reversal code:": "115",
    "savings - cob:": "106",
    "savings – negotiated fee:": "104",
    "savings – r&c:": "105",
    "savings – source cob:": "107",
    "service benefit code:": "75",
    "servicing provider city:": "51",
    "servicing provider class code:": "124",
    "servicing provider name": "48",
    "servicing provider network id:": "40",
    "servicing provider npi:": "134",
    "servicing provider pin:": "47",
    "servicing provider specialty category code:": "133",
    "servicing provider specialty code:": "55",
    "servicing provider state:": "52",
    "servicing provider street address 1:": "49",
    "servicing provider street address 2:": "50",
    "servicing provider tax id number": "46",
    "servicing provider type class code:": "132",
    "servicing provider type:": "54",
    "servicing provider zip code:": "53",
    "source coinsurance amount:": "98",
    "source copayment amount:": "95",
    "source number/units of service:": "82",
    "source system platform:": "7",
    "source-specific transaction id number:": "33",
    "status of claim:": "113",
    "subscriber date of birth:": "21",
    "subscriber first name or initial:": "19",
    "subscriber gender:": "20",
    "subscriber last name:": "18",
    "subscriber state:": "23",
    "subscriber zip code:": "22",
    "tooth number:": "76",
    "total deductible met indicator:": "135",
    "total interest amount:": "136",
    "total surcharge amount:": "137",
    "traditional claim id:": "36",
    "type of expense - cob:": "109",
    "type of service:": "74",
    "ub92 bill type:": "80",
    "ub92 patient/discharge status:": "78",
    "ub92 revenue center:": "79",
    "void the original claim, and reprocess using a different claim id": "2",
}
